name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Application
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Test Backend
      run: |
        cd server
        npm ci
        npm test
      env:
        NODE_ENV: test
        MONGO_URL: ${{ secrets.MONGO_URL_TEST }}
        JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}
      continue-on-error: true
    
    - name: Test Frontend
      run: |
        cd Client
        npm ci
        npm test -- --coverage --watchAll=false
      env:
        NODE_ENV: test
        REACT_APP_API_URL: http://localhost:5000
      continue-on-error: true

  build:
    runs-on: ubuntu-latest
    name: Build Docker Images
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: false
        tags: agriconnect-backend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./Client
        file: ./Client/Dockerfile
        push: false
        tags: agriconnect-frontend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/agriconnect-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/agriconnect-backend:${{ github.sha }}
    
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./Client
        file: ./Client/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/agriconnect-frontend:latest
          ${{ secrets.DOCKER_USERNAME }}/agriconnect-frontend:${{ github.sha }}